{% set name = "xontrib-prompt-bar" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bce4cc11f9f08a5ac70cf5ce4138b33806e972a9d5c693d22c129f97da437658

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh

test:
  commands:
    - xonsh -c "xontrib load prompt_bar"

about:
  home: https://github.com/anki-code/xontrib-prompt-bar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bar theme for xonsh shell
  doc_url: https://github.com/anki-code/xontrib-prompt-bar/blob/master/README.md
  dev_url: https://github.com/anki-code/xontrib-prompt-bar

extra:
  recipe-maintainers:
    - scopatz
